### ISSUE TITLE
port not recognizing

### ISSUE THREAD

**Issue by nihalsahu** [ghoshnirmalya/linkedin-react#28]
> PORT=3001 react-scripts start

'PORT' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! linkedin-react@0.0.1 start: `PORT=3001 react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the linkedin-react@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nihasahu\AppData\Roaming\npm-cache\_logs\2019-04-19T04_22_12_863Z-debug.log

**Comment by ghoshnirmalya** [comment]
I think that you're using Windows. You need to change the `start` script to:
```
"scripts": {
    "start": "set PORT=3001 && react-scripts start",
    ....
```

For more details, see https://github.com/facebook/create-react-app/issues/1083#issuecomment-318836463 and the whole thread.
